version: 2

sources:
  - name: olist_raw_sources
    database: "{{ target.project }}" 
    schema: olist_raw
    tables:
      # Core Tables (Used for core assignment math)
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_customers_dataset
      - name: olist_products_dataset
      - name: product_category_name_translation
      
      # Additional Tables (Available for extended Star Schema)
      - name: olist_sellers_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_geolocation_dataset